import React, { createContext, useContext, useState } from 'react';

const translations = {
  fr: {
    siteTitle: "Apiculture E-commerce",
    siteSubtitle: "Votre partenaire professionnel en apiculture",
    home: "Accueil",
    products: "Produits",
    equipment: "Équipement", 
    honey: "Miel",
    training: "Formation",
    contact: "Contact",
    welcome: "Bienvenue dans votre boutique d'apiculture",
    heroText: "Matériel professionnel, miels premium et formations expertes",
    discoverProducts: "Découvrir nos produits",
    freeConsultation: "Consultation gratuite",
    ourCategories: "Nos Catégories",
    beekeepingEquipment: "Matériel Apiculture",
    equipmentDesc: "Ruches, équipements, protection",
    honeyProducts: "Miel & Produits Dérivés", 
    honeyDesc: "Miels premium, propolis, pollen",
    trainingCourses: "Formation & Cours",
    trainingDesc: "Cours en ligne, guides PDF, webinaires",
    starterKits: "Kits Débutants",
    starterDesc: "Solutions clés en main",
    rightsReserved: "Tous droits réservés",
    madeIn: "siham lakmichi",
    
    // Traductions communes
    all: "Tous",
    origin: "Origine",
    weight: "Poids",
    addToCart: "Ajouter au panier",
    shoppingCart: "Panier",
    items: "articles",
    cartEmpty: "Votre panier est vide",
    totalAmount: "Montant total",
    proceedToCheckout: "Passer à la caisse",
    addedToCart: "a été ajouté au panier",
    contact: "Contact",
    shippingInfo: "Livraison",
    rightsReserved: "Tous droits réservés",
    
    // Traductions pour le composant Hony (miel)
    honeyTagline: "Miel allemand de qualité premium",
    ourHoneyVarieties: "Nos variétés de miel",
    classic: "Classique",
    blossomHoney: "Miel de fleurs",
    forestHoney: "Miel de forêt",
    whyGermanHoney: "Pourquoi du miel allemand ?",
    supportLocalBeekeepers: "Soutien aux apiculteurs locaux",
    shortTransportRoutes: "Trajets de transport courts",
    strictQualityControl: "Contrôle qualité strict",
    sustainableBeekeeping: "Apiculture durable",
    honeyShop: "Boutique de miel",
    footerDescription: "Votre source de miel allemand de qualité",
    
    // Noms et descriptions des produits Hony
    akazienHonigName: "Miel d'acacia",
    akazienHonigDesc: "Miel doux et clair avec un arôme délicat de fleur d'acacia. Parfait pour sucrer les boissons.",
    lavenderHonigName: "Miel de lavande",
    lavenderHonigDesc: "Miel aromatique avec des notes florales de lavande. Idéal pour les infusions et les pâtisseries.",
    forestHoneyName: "Miel de forêt",
    forestHoneyDesc: "Miel robuste au goût prononcé, riche en minéraux. Provenant des forêts de sapins et de chênes.",
    lindenHoneyName: "Miel de tilleul",
    lindenHoneyDesc: "Miel fin avec un subtil goût de fleur de tilleul. Excellent pour la digestion.",
    rapeseedHoneyName: "Miel de colza",
    rapeseedHoneyDesc: "Miel crémeux et clair au goût doux. Parfait pour le pain et le petit-déjeuner.",
    firHoneyName: "Miel de sapin",
    firHoneyDesc: "Miel foncé et épicé avec des notes résineuses. Particulièrement riche en minéraux.",
    
    // Régions Hony
    germany: "Allemagne",
    bavaria: "Bavière",
    blackForest: "Forêt-Noire",
    hesse: "Hesse",
    lowerSaxony: "Basse-Saxe",
    
    // Traductions pour le composant Tea (thé)
    teaTagline: "Thés fins de qualité supérieure",
    ourTeaVarieties: "Nos variétés de thé",
    blackTea: "Thé noir",
    greenTea: "Thé vert",
    herbalTea: "Tisanes",
    fruitTea: "Thé aux fruits",
    whyQualityTea: "Pourquoi un thé de qualité ?",
    premiumSelection: "Sélection premium rigoureuse",
    directFromProducer: "Directement du producteur",
    freshlyPackaged: "Emballé fraîchement",
    sustainableCultivation: "Culture durable",
    fairTrade: "Commerce équitable",
    teaShop: "Boutique de thé",
    teaShopDescription: "Votre spécialiste en thés fins du monde entier",
    shippingDetails: "Livraison gratuite à partir de 30€",
    brewingTips: "Conseils d'infusion",
    brewingDescription: "Pour une infusion parfaite : eau à température adaptée (80°C pour le thé vert, 100°C pour le thé noir) et temps d'infusion de 2-5 minutes selon le type de thé.",
    
    // Noms et descriptions des thés
    earlGreyName: "Earl Grey",
    earlGreyDesc: "Thé noir aromatisé à la bergamote, doux et parfumé. Parfait pour le thé de l'après-midi.",
    jasmineTeaName: "Thé au jasmin",
    jasmineTeaDesc: "Thé vert parfumé aux fleurs de jasmin, délicat et floral. Idéal pour la détente.",
    chamomileTeaName: "Camomille",
    chamomileTeaDesc: "Infusion apaisante de fleurs de camomille. Parfaite pour le soir avant le coucher.",
    peppermintTeaName: "Thé à la menthe poivrée",
    peppermintTeaDesc: "Tisane rafraîchissante à la menthe, digestive et tonifiante.",
    darjeelingName: "Darjeeling",
    darjeelingDesc: "Thé noir indien délicat au goût muscaté. Le 'champagne des thés'.",
    berryTeaName: "Thé aux fruits rouges",
    berryTeaDesc: "Mélange fruité de baies, naturellement sans caféine. Doux et fruité.",
    matchaName: "Matcha",
    matchaDesc: "Thé vert japonais en poudre, riche en antioxydants. Énergisant et détoxifiant.",
    rooibosName: "Rooibos",
    rooibosDesc: "Infusion sud-africaine naturellement sans caféine, douce et légèrement sucrée.",
    
    // Régions Tea
    england: "Angleterre",
    china: "Chine",
    egypt: "Égypte",
    morocco: "Maroc",
    india: "Inde",
    japan: "Japon",
    southAfrica: "Afrique du Sud",
    
    // Traductions pour le composant OliveOil (huile d'olive)
    oliveOilTagline: "Huiles d'olive extra vierge premium",
    ourOliveOilVarieties: "Nos variétés d'huile d'olive",
    extraVirginOliveOil: "Extra vierge",
    virginOliveOil: "Vierge",
    organicOliveOil: "Biologique",
    flavoredOliveOil: "Aromatisée",
    acidity: "Acidité",
    volume: "Volume",
    whyQualityOliveOil: "Pourquoi une huile d'olive de qualité ?",
    coldPressed: "Pressée à froid",
    firstColdPress: "Première pression à froid",
    lowAcidity: "Faible acidité",
    richInPolyphenols: "Riche en polyphénols",
    sustainableFarming: "Agriculture durable",
    oliveOilShop: "Boutique d'huile d'olive",
    oliveOilShopDescription: "Votre spécialiste en huiles d'olive extra vierge",
    shippingDetailsOliveOil: "Livraison gratuite à partir de 50€",
    storageTips: "Conseils de conservation",
    storageDescription: "Conserver à l'abri de la lumière et de la chaleur, idéalement entre 14-18°C. Bien refermer après utilisation.",
    
    // Noms et descriptions des huiles d'olive
    extraVirginPremiumName: "Extra Vierge Premium",
    extraVirginPremiumDesc: "Huile d'olive extra vierge de première qualité, fruitée et légèrement amère. Parfaite pour les salades.",
    tuscanOliveOilName: "Huile d'olive de Toscane",
    tuscanOliveOilDesc: "Huile d'olive toscane robuste avec des notes d'artichaut et de poivre. Idéale pour les pâtes.",
    lemonOliveOilName: "Huile d'olive au citron",
    lemonOliveOilDesc: "Huile d'olive extra vierge aromatisée au zeste de citron frais. Parfaite pour le poisson.",
    organicOliveOilName: "Huile d'olive biologique",
    organicOliveOilDesc: "Huile d'olive extra vierge certifiée biologique, douce et équilibrée.",
    garlicOliveOilName: "Huile d'olive à l'ail",
    garlicOliveOilDesc: "Huile d'olive aromatisée à l'ail frais. Parfaite pour les plats méditerranéens.",
    virginOliveOilName: "Huile d'olive vierge",
    virginOliveOilDesc: "Huile d'olive vierge, légèrement plus fruitée, idéale pour la cuisson.",
    basilOliveOilName: "Huile d'olive au basilic",
    basilOliveOilDesc: "Huile d'olive aromatisée au basilic frais. Excellente pour les tomates et les salades.",
    bioOrganicOilName: "Huile d'olive bio premium",
    bioOrganicOilDesc: "Huile d'olive extra vierge biologique premium, très faible acidité, goût exceptionnel.",
    
    // Régions OliveOil
    andalusia: "Andalousie",
    tuscany: "Toscane",
    sicily: "Sicile",
    crete: "Crète",
    apulia: "Pouilles",
    provence: "Provence",
    liguria: "Ligurie",
    catalonia: "Catalogne"
  },
  de: {
    siteTitle: "Imkerei E-Commerce",
    siteSubtitle: "Ihr professioneller Partner für Bienenzucht",
    home: "Startseite",
    products: "Produkte", 
    equipment: "Ausrüstung",
    honey: "Honig",
    training: "Schulung",
    contact: "Kontakt",
    welcome: "Willkommen in Ihrem Imkerei-Fachgeschäft",
    heroText: "Professionelle Ausrüstung, Premium-Honig und Experten-Schulungen",
    discoverProducts: "Produkte entdecken",
    freeConsultation: "Kostenlose Beratung",
    ourCategories: "Unsere Kategorien",
    beekeepingEquipment: "Imkerei-Ausrüstung",
    equipmentDesc: "Bienenstöcke, Schutzkleidung, Werkzeuge",
    honeyProducts: "Honig & Produkte",
    honeyDesc: "Premium-Honig, Propolis, Pollen", 
    trainingCourses: "Schulung & Kurse",
    trainingDesc: "Online-Kurse, PDF-Anleitungen, Webinare",
    starterKits: "Starter-Kits",
    starterDesc: "Alles-in-Einem-Lösungen für Anfänger",
    rightsReserved: "Alle Rechte vorbehalten",
    madeIn: "Made in Germany",
    
    // Traductions communes
    all: "Alle",
    origin: "Herkunft",
    weight: "Gewicht",
    addToCart: "In den Warenkorb",
    shoppingCart: "Warenkorb",
    items: "Artikel",
    cartEmpty: "Ihr Warenkorb ist leer",
    totalAmount: "Gesamtsumme",
    proceedToCheckout: "Zur Kasse gehen",
    addedToCart: "wurde zum Warenkorb hinzugefügt",
    contact: "Kontakt",
    shippingInfo: "Versand",
    rightsReserved: "Alle Rechte vorbehalten",
    
    // Traductions pour le composant Hony (miel)
    honeyTagline: "Deutscher Honig in Premium-Qualität",
    ourHoneyVarieties: "Unsere Honigsorten",
    classic: "Klassisch",
    blossomHoney: "Blütenhonig",
    forestHoney: "Waldhonig",
    whyGermanHoney: "Warum deutscher Honig?",
    supportLocalBeekeepers: "Unterstützung lokaler Imker",
    shortTransportRoutes: "Kurze Transportwege",
    strictQualityControl: "Streng kontrollierte Qualität",
    sustainableBeekeeping: "Nachhaltige Bienenzucht",
    honeyShop: "Honig Shop",
    footerDescription: "Ihre Quelle für deutschen Qualitätshonig",
    
    // Noms et descriptions des produits Hony
    akazienHonigName: "Akazienhonig",
    akazienHonigDesc: "Milder, klarer Honig mit zartem Akazienblütenaroma. Perfekt zum Süßen von Getränken.",
    lavenderHonigName: "Lavendelhonig",
    lavenderHonigDesc: "Aromatischer Honig mit blumigen Lavendelnoten. Ideal für Aufgüsse und Gebäck.",
    forestHoneyName: "Waldhonig",
    forestHoneyDesc: "Kräftiger Honig mit ausgeprägtem Geschmack, reich an Mineralien. Aus Tannen- und Eichenwäldern.",
    lindenHoneyName: "Lindenhonig",
    lindenHoneyDesc: "Feiner Honig mit subtilem Lindenblütengeschmack. Hervorragend für die Verdauung.",
    rapeseedHoneyName: "Rapshonig",
    rapeseedHoneyDesc: "Cremiger, heller Honig mit mildem Geschmack. Perfekt für Brot und Frühstück.",
    firHoneyName: "Tannenhonig",
    firHoneyDesc: "Dunkler, würziger Honig mit harzigen Noten. Besonders mineralstoffreich.",
    
    // Régions Hony
    germany: "Deutschland",
    bavaria: "Bayern",
    blackForest: "Schwarzwald",
    hesse: "Hessen",
    lowerSaxony: "Niedersachsen",
    
    // Traductions pour le composant Tea (thé)
    teaTagline: "Feinste Teesorten in Premium-Qualität",
    ourTeaVarieties: "Unsere Teesorten",
    blackTea: "Schwarzer Tee",
    greenTea: "Grüner Tee",
    herbalTea: "Kräutertee",
    fruitTea: "Früchtetee",
    whyQualityTea: "Warum Qualitätstee?",
    premiumSelection: "Strengste Premium-Auswahl",
    directFromProducer: "Direkt vom Erzeuger",
    freshlyPackaged: "Frisch verpackt",
    sustainableCultivation: "Nachhaltiger Anbau",
    fairTrade: "Fairen Handel",
    teaShop: "Tee-Spezialitäten",
    teaShopDescription: "Ihr Spezialist für feinste Tees aus aller Welt",
    shippingDetails: "Kostenloser Versand ab 30€",
    brewingTips: "Zubereitungstipps",
    brewingDescription: "Für die perfekte Tasse Tee: Wasser mit passender Temperatur (80°C für grünen Tee, 100°C für schwarzen Tee) und Ziehzeit von 2-5 Minuten je nach Teesorte.",
    
    // Noms et descriptions des thés
    earlGreyName: "Earl Grey",
    earlGreyDesc: "Schwarzer Tee mit Bergamotte-Aroma, mild und wohlriechend. Perfekt für den Nachmittagstee.",
    jasmineTeaName: "Jasmintee",
    jasmineTeaDesc: "Grüner Tee mit Jasminblüten, zart und blumig. Ideal zur Entspannung.",
    chamomileTeaName: "Kamillentee",
    chamomileTeaDesc: "Beruhigender Aufguss aus Kamillenblüten. Perfekt für den Abend vor dem Schlafengehen.",
    peppermintTeaName: "Pfefferminztee",
    peppermintTeaDesc: "Erfrischender Kräuteraufguss mit Minze, verdauungsfördernd und belebend.",
    darjeelingName: "Darjeeling",
    darjeelingDesc: "Zarter indischer Schwarztee mit muskatartigem Geschmack. Der 'Champagner der Tees'.",
    berryTeaName: "Beerentee",
    berryTeaDesc: "Fruchtige Beerenmischung, natürlich koffeinfrei. Mild und fruchtig.",
    matchaName: "Matcha",
    matchaDesc: "Japanischer Grüntee in Pulverform, reich an Antioxidantien. Belebend und entgiftend.",
    rooibosName: "Rooibos",
    rooibosDesc: "Südafrikanischer Aufguss, natürlich koffeinfrei, mild und leicht süßlich.",
    
    // Régions Tea
    england: "England",
    china: "China",
    egypt: "Ägypten",
    morocco: "Marokko",
    india: "Indien",
    japan: "Japan",
    southAfrica: "Südafrika",
    
    // Traductions pour le composant OliveOil (huile d'olive)
    oliveOilTagline: "Premium Olivenöle extra vergine",
    ourOliveOilVarieties: "Unsere Olivenölsorten",
    extraVirginOliveOil: "Extra vergine",
    virginOliveOil: "Vergine",
    organicOliveOil: "Bio",
    flavoredOliveOil: "Aromatisiert",
    acidity: "Säuregehalt",
    volume: "Volumen",
    whyQualityOliveOil: "Warum Qualitäts-Olivenöl?",
    coldPressed: "Kaltgepresst",
    firstColdPress: "Erste Kaltpressung",
    lowAcidity: "Niedriger Säuregehalt",
    richInPolyphenols: "Reich an Polyphenolen",
    sustainableFarming: "Nachhaltiger Anbau",
    oliveOilShop: "Olivenöl-Spezialitäten",
    oliveOilShopDescription: "Ihr Spezialist für extra vergine Olivenöle",
    shippingDetailsOliveOil: "Kostenloser Versand ab 50€",
    storageTips: "Lagerungstipps",
    storageDescription: "Vor Licht und Wärme geschützt lagern, ideal bei 14-18°C. Nach Gebrauch gut verschließen.",
    
    // Noms et descriptions des huiles d'olive
    extraVirginPremiumName: "Extra Vergine Premium",
    extraVirginPremiumDesc: "Hochwertiges natives Olivenöl extra, fruchtig und leicht bitter. Perfekt für Salate.",
    tuscanOliveOilName: "Toskanisches Olivenöl",
    tuscanOliveOilDesc: "Kräftiges toskanisches Olivenöl mit Artischocken- und Pfeffernoten. Ideal für Pasta.",
    lemonOliveOilName: "Zitronen-Olivenöl",
    lemonOliveOilDesc: "Natives Olivenöl extra mit frischer Zitronenschale aromatisiert. Perfekt für Fisch.",
    organicOliveOilName: "Bio Olivenöl",
    organicOliveOilDesc: "Zertifiziertes natives Olivenöl extra aus biologischem Anbau, mild und ausgewogen.",
    garlicOliveOilName: "Knoblauch-Olivenöl",
    garlicOliveOilDesc: "Mit frischem Knoblauch aromatisiertes Olivenöl. Perfekt für mediterrane Gerichte.",
    virginOliveOilName: "Natives Olivenöl",
    virginOliveOilDesc: "Natives Olivenöl, etwas fruchtiger, ideal zum Kochen.",
    basilOliveOilName: "Basilikum-Olivenöl",
    basilOliveOilDesc: "Mit frischem Basilikum aromatisiertes Olivenöl. Ausgezeichnet für Tomaten und Salate.",
    bioOrganicOilName: "Bio Premium Olivenöl",
    bioOrganicOilDesc: "Premium natives Olivenöl extra aus biologischem Anbau, sehr niedriger Säuregehalt, außergewöhnlicher Geschmack.",
    
    // Régions OliveOil
    andalusia: "Andalusien",
    tuscany: "Toskana",
    sicily: "Sizilien",
    crete: "Kreta",
    apulia: "Apulien",
    provence: "Provence",
    liguria: "Ligurien",
    catalonia: "Katalonien"
  },
  en: {
    siteTitle: "Beekeeping E-commerce", 
    siteSubtitle: "Your professional beekeeping partner",
    home: "Home",
    products: "Products",
    equipment: "Equipment",
    honey: "Honey",
    training: "Training",
    contact: "Contact",
    welcome: "Welcome to your beekeeping store",
    heroText: "Professional equipment, premium honey and expert training",
    discoverProducts: "Discover our products", 
    freeConsultation: "Free consultation",
    ourCategories: "Our Categories",
    beekeepingEquipment: "Beekeeping Equipment",
    equipmentDesc: "Hives, equipment, protection",
    honeyProducts: "Honey & Products",
    honeyDesc: "Premium honey, propolis, pollen",
    trainingCourses: "Training & Courses",
    trainingDesc: "Online courses, PDF guides, webinars",
    starterKits: "Starter Kits",
    starterDesc: "All-in-one solutions for beginners",
    rightsReserved: "All rights reserved", 
    madeIn: "Made with passion",
    
    // Traductions communes
    all: "All",
    origin: "Origin",
    weight: "Weight",
    addToCart: "Add to cart",
    shoppingCart: "Shopping cart",
    items: "items",
    cartEmpty: "Your cart is empty",
    totalAmount: "Total amount",
    proceedToCheckout: "Proceed to checkout",
    addedToCart: "has been added to cart",
    contact: "Contact",
    shippingInfo: "Shipping",
    rightsReserved: "All rights reserved",
    
    // Traductions pour le composant Hony (miel)
    honeyTagline: "German honey in premium quality",
    ourHoneyVarieties: "Our honey varieties",
    classic: "Classic",
    blossomHoney: "Blossom honey",
    forestHoney: "Forest honey",
    whyGermanHoney: "Why German honey?",
    supportLocalBeekeepers: "Support local beekeepers",
    shortTransportRoutes: "Short transport routes",
    strictQualityControl: "Strict quality control",
    sustainableBeekeeping: "Sustainable beekeeping",
    honeyShop: "Honey shop",
    footerDescription: "Your source for German quality honey",
    
    // Noms et descriptions des produits Hony
    akazienHonigName: "Acacia honey",
    akazienHonigDesc: "Mild, clear honey with delicate acacia blossom aroma. Perfect for sweetening beverages.",
    lavenderHonigName: "Lavender honey",
    lavenderHonigDesc: "Aromatic honey with floral lavender notes. Ideal for infusions and baked goods.",
    forestHoneyName: "Forest honey",
    forestHoneyDesc: "Robust honey with pronounced taste, rich in minerals. From fir and oak forests.",
    lindenHoneyName: "Linden honey",
    lindenHoneyDesc: "Fine honey with subtle linden blossom flavor. Excellent for digestion.",
    rapeseedHoneyName: "Rapeseed honey",
    rapeseedHoneyDesc: "Creamy, light honey with mild taste. Perfect for bread and breakfast.",
    firHoneyName: "Fir honey",
    firHoneyDesc: "Dark, spicy honey with resinous notes. Particularly rich in minerals.",
    
    // Régions Hony
    germany: "Germany",
    bavaria: "Bavaria",
    blackForest: "Black Forest",
    hesse: "Hesse",
    lowerSaxony: "Lower Saxony",
    
    // Traductions pour le composant Tea (thé)
    teaTagline: "Premium quality fine teas",
    ourTeaVarieties: "Our tea varieties",
    blackTea: "Black tea",
    greenTea: "Green tea",
    herbalTea: "Herbal tea",
    fruitTea: "Fruit tea",
    whyQualityTea: "Why quality tea?",
    premiumSelection: "Strict premium selection",
    directFromProducer: "Direct from producer",
    freshlyPackaged: "Freshly packaged",
    sustainableCultivation: "Sustainable cultivation",
    fairTrade: "Fair trade",
    teaShop: "Tea shop",
    teaShopDescription: "Your specialist for finest teas from around the world",
    shippingDetails: "Free shipping from 30€",
    brewingTips: "Brewing tips",
    brewingDescription: "For the perfect cup of tea: water at the right temperature (80°C for green tea, 100°C for black tea) and steeping time of 2-5 minutes depending on tea type.",
    
    // Noms et descriptions des thés
    earlGreyName: "Earl Grey",
    earlGreyDesc: "Black tea flavored with bergamot, mild and fragrant. Perfect for afternoon tea.",
    jasmineTeaName: "Jasmine tea",
    jasmineTeaDesc: "Green tea scented with jasmine flowers, delicate and floral. Ideal for relaxation.",
    chamomileTeaName: "Chamomile tea",
    chamomileTeaDesc: "Soothing chamomile flower infusion. Perfect for evening before bedtime.",
    peppermintTeaName: "Peppermint tea",
    peppermintTeaDesc: "Refreshing herbal infusion with mint, digestive and invigorating.",
    darjeelingName: "Darjeeling",
    darjeelingDesc: "Delicate Indian black tea with muscatel flavor. The 'champagne of teas'.",
    berryTeaName: "Berry tea",
    berryTeaDesc: "Fruity berry blend, naturally caffeine-free. Mild and fruity.",
    matchaName: "Matcha",
    matchaDesc: "Japanese green tea powder, rich in antioxidants. Energizing and detoxifying.",
    rooibosName: "Rooibos",
    rooibosDesc: "South African infusion, naturally caffeine-free, mild and slightly sweet.",
    
    // Régions Tea
    england: "England",
    china: "China",
    egypt: "Egypt",
    morocco: "Morocco",
    india: "India",
    japan: "Japan",
    southAfrica: "South Africa",
    
    // Traductions pour le composant OliveOil (huile d'olive)
    oliveOilTagline: "Premium extra virgin olive oils",
    ourOliveOilVarieties: "Our olive oil varieties",
    extraVirginOliveOil: "Extra virgin",
    virginOliveOil: "Virgin",
    organicOliveOil: "Organic",
    flavoredOliveOil: "Flavored",
    acidity: "Acidity",
    volume: "Volume",
    whyQualityOliveOil: "Why quality olive oil?",
    coldPressed: "Cold pressed",
    firstColdPress: "First cold press",
    lowAcidity: "Low acidity",
    richInPolyphenols: "Rich in polyphenols",
    sustainableFarming: "Sustainable farming",
    oliveOilShop: "Olive oil shop",
    oliveOilShopDescription: "Your specialist for extra virgin olive oils",
    shippingDetailsOliveOil: "Free shipping from 50€",
    storageTips: "Storage tips",
    storageDescription: "Store away from light and heat, ideally at 14-18°C. Close tightly after use.",
    
    // Noms et descriptions des huiles d'olive
    extraVirginPremiumName: "Extra Virgin Premium",
    extraVirginPremiumDesc: "High quality extra virgin olive oil, fruity and slightly bitter. Perfect for salads.",
    tuscanOliveOilName: "Tuscan Olive Oil",
    tuscanOliveOilDesc: "Robust Tuscan olive oil with artichoke and pepper notes. Ideal for pasta.",
    lemonOliveOilName: "Lemon Olive Oil",
    lemonOliveOilDesc: "Extra virgin olive oil flavored with fresh lemon zest. Perfect for fish.",
    organicOliveOilName: "Organic Olive Oil",
    organicOliveOilDesc: "Certified organic extra virgin olive oil, mild and balanced.",
    garlicOliveOilName: "Garlic Olive Oil",
    garlicOliveOilDesc: "Olive oil flavored with fresh garlic. Perfect for Mediterranean dishes.",
    virginOliveOilName: "Virgin Olive Oil",
    virginOliveOilDesc: "Virgin olive oil, slightly fruitier, ideal for cooking.",
    basilOliveOilName: "Basil Olive Oil",
    basilOliveOilDesc: "Olive oil flavored with fresh basil. Excellent for tomatoes and salads.",
    bioOrganicOilName: "Bio Premium Olive Oil",
    bioOrganicOilDesc: "Premium organic extra virgin olive oil, very low acidity, exceptional taste.",
    
    // Régions OliveOil
    andalusia: "Andalusia",
    tuscany: "Tuscany",
    sicily: "Sicily",
    crete: "Crete",
    apulia: "Apulia",
    provence: "Provence",
    liguria: "Liguria",
    catalonia: "Catalonia"
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('de');

  const t = (key) => {
    return translations[language]?.[key] || key;
  };

  const changeLanguage = (lng) => {
    setLanguage(lng);
  };

  const value = {
    language,
    t,
    changeLanguage
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};